# Based on Nodejs template

# https://hub.docker.com/r/library/node/tags/
image: node:lts-slim

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:
  script:
    - npm install
    - npm test
    - npm run lint
